import { createContext, useContext, useState, ReactNode } from 'react';

interface Translations {
  // Welcome & Auth
  welcome: string;
  selectLanguage: string;
  getStarted: string;
  defencePlatform: string;
  enterPhone: string;
  phoneNumber: string;
  sendOTP: string;
  newUser: string;
  familyJoin: string;
  encrypted: string;
  
  // Registration
  register: string;
  createAccount: string;
  fullName: string;
  serviceId: string;
  aadhaarNumber: string;
  alreadyHaveAccount: string;
  loginHere: string;
  familyMemberRegistration: string;
  joinViaReference: string;
  referenceId: string;
  selectRelation: string;
  chooseFile: string;
  joinAsFamilyMember: string;
  spouse: string;
  parent: string;
  child: string;
  sibling: string;
  
  // Main App
  chats: string;
  communities: string;
  broadcasts: string;
  calls: string;
  settings: string;
  profile: string;
  searchChats: string;
  typeMessage: string;
  selectChatToStart: string;
  selectCommunity: string;
  selectBroadcast: string;
  members: string;
  recipients: string;
  
  // Profile
  editProfile: string;
  logout: string;
  verifiedAccount: string;
  
  // Settings
  account: string;
  privacy: string;
  security: string;
  preferences: string;
  darkMode: string;
  notifications: string;
  about: string;
  aboutSuchak: string;
  e2eInfo: string;
  
  // Calls
  calling: string;
  missed: string;
  endCall: string;
  
  // Messages
  online: string;
  offline: string;
  yesterday: string;
  
  // Common
  required: string;
  submit: string;
  cancel: string;
}

const englishTranslations: Translations = {
  welcome: 'Welcome to SUCHAK',
  selectLanguage: 'Select a language to continue',
  getStarted: 'Get Started',
  defencePlatform: 'Defence Communication Platform',
  enterPhone: 'Enter Your Phone Number',
  phoneNumber: 'Phone Number',
  sendOTP: 'Send OTP',
  newUser: 'New Govt User? Register Here',
  familyJoin: 'Join as Family Member (Scan/Ref ID)',
  encrypted: 'End-to-end encrypted',
  register: 'Register',
  createAccount: 'Create your secure account',
  fullName: 'Full Name',
  serviceId: 'Service ID / Veteran ID',
  aadhaarNumber: 'Aadhaar Number',
  alreadyHaveAccount: 'Already have an account?',
  loginHere: 'Login',
  familyMemberRegistration: 'Family Member Registration',
  joinViaReference: 'Join via Reference ID & Verification',
  referenceId: 'Reference ID',
  selectRelation: 'Select Relation',
  chooseFile: 'Choose File',
  joinAsFamilyMember: 'Join as Family Member',
  spouse: 'Spouse',
  parent: 'Parent',
  child: 'Child',
  sibling: 'Sibling',
  chats: 'Chats',
  communities: 'Communities',
  broadcasts: 'Broadcasts',
  calls: 'Calls',
  settings: 'Settings',
  profile: 'Profile',
  searchChats: 'Search chats...',
  typeMessage: 'Type a message...',
  selectChatToStart: 'Select a chat to start messaging',
  selectCommunity: 'Select a community to view',
  selectBroadcast: 'Select a broadcast to view',
  members: 'members',
  recipients: 'recipients',
  editProfile: 'Edit Profile',
  logout: 'Logout',
  verifiedAccount: 'Verified Account',
  account: 'Account',
  privacy: 'Privacy',
  security: 'Security',
  preferences: 'Preferences',
  darkMode: 'Dark Mode',
  notifications: 'Notifications',
  about: 'About',
  aboutSuchak: 'About SUCHAK',
  e2eInfo: 'E2E Encryption Info',
  calling: 'Calling...',
  missed: 'Missed',
  endCall: 'End Call',
  online: 'online',
  offline: 'offline',
  yesterday: 'Yesterday',
  required: '*',
  submit: 'Submit',
  cancel: 'Cancel',
};

const translations: Record<string, Translations> = {
  english: englishTranslations,
  hindi: { ...englishTranslations, ...{
    welcome: 'SUCHAK में आपका स्वागत है',
    selectLanguage: 'जारी रखने के लिए भाषा चुनें',
    getStarted: 'शुरू करें',
    defencePlatform: 'रक्षा संचार मंच',
    enterPhone: 'अपना फ़ोन नंबर दर्ज करें',
    phoneNumber: 'फ़ोन नंबर',
    sendOTP: 'OTP भेजें',
    newUser: 'नए सरकारी उपयोगकर्ता? यहां पंजीकरण करें',
    familyJoin: 'परिवार के सदस्य के रूप में शामिल हों',
    encrypted: 'एंड-टू-एंड एन्क्रिप्टेड',
    register: 'पंजीकरण करें',
    createAccount: 'अपना सुरक्षित खाता बनाएं',
    fullName: 'पूरा नाम',
    serviceId: 'सेवा आईडी / वयोवृद्ध आईडी',
    aadhaarNumber: 'आधार नंबर',
    alreadyHaveAccount: 'क्या आपके पास पहले से खाता है?',
    loginHere: 'लॉगिन करें',
    familyMemberRegistration: 'परिवार के सदस्य का पंजीकरण',
    joinViaReference: 'संदर्भ आईडी और सत्यापन के माध्यम से शामिल हों',
    referenceId: 'संदर्भ आईडी',
    selectRelation: 'संबंध चुनें',
    chooseFile: 'फ़ाइल चुनें',
    joinAsFamilyMember: 'परिवार के सदस्य के रूप में शामिल हों',
    spouse: 'पति/पत्नी',
    parent: 'माता-पिता',
    child: 'बच्चा',
    sibling: 'भाई/बहन',
    chats: 'चैट',
    communities: 'समुदाय',
    broadcasts: 'प्रसारण',
    calls: 'कॉल',
    settings: 'सेटिंग्स',
    profile: 'प्रोफ़ाइल',
    searchChats: 'चैट खोजें...',
    typeMessage: 'संदेश लिखें...',
    selectChatToStart: 'संदेश शुरू करने के लिए चैट चुनें',
    selectCommunity: 'देखने के लिए समुदाय चुनें',
    selectBroadcast: 'देखने के लिए प्रसारण चुनें',
    members: 'सदस्य',
    recipients: 'प्राप्तकर्ता',
    editProfile: 'प्रोफ़ाइल संपादित करें',
    logout: 'लॉगआउट',
    verifiedAccount: 'सत्यापित खाता',
    account: 'खाता',
    privacy: 'गोपनीयता',
    security: 'सुरक्षा',
    preferences: 'प्राथमिकताएं',
    darkMode: 'डार्क मोड',
    notifications: 'सूचनाएं',
    about: 'के बारे में',
    aboutSuchak: 'SUCHAK के बारे में',
    e2eInfo: 'E2E एन्क्रिप्शन जानकारी',
    calling: 'कॉल कर रहे हैं...',
    missed: 'छूटी हुई',
    endCall: 'कॉल समाप्त करें',
    online: 'ऑनलाइन',
    offline: 'ऑफ़लाइन',
    yesterday: 'कल',
    submit: 'जमा करें',
    cancel: 'रद्द करें',
  }},
  marathi: { ...englishTranslations, ...{
    welcome: 'SUCHAK मध्ये आपले स्वागत आहे',
    selectLanguage: 'सुरू ठेवण्यासाठी भाषा निवडा',
    getStarted: 'सुरू करा',
    defencePlatform: 'संरक्षण संवाद व्यासपीठ',
    enterPhone: 'आपला फोन नंबर प्रविष्ट करा',
    phoneNumber: 'फोन नंबर',
    sendOTP: 'OTP पाठवा',
    newUser: 'नवीन सरकारी वापरकर्ता? येथे नोंदणी करा',
    familyJoin: 'कुटुंब सदस्य म्हणून सामील व्हा',
    encrypted: 'एंड-टू-एंड एन्क्रिप्टेड',
    register: 'नोंदणी करा',
    createAccount: 'आपले सुरक्षित खाते तयार करा',
    fullName: 'पूर्ण नाव',
    serviceId: 'सेवा आयडी / वेटरन आयडी',
    aadhaarNumber: 'आधार क्रमांक',
    alreadyHaveAccount: 'आधीपासून खाते आहे?',
    loginHere: 'लॉगिन',
    familyMemberRegistration: 'कुटुंब सदस्य नोंदणी',
    joinViaReference: 'संदर्भ आयडी आणि पडताळणी द्वारे सामील व्हा',
    referenceId: 'संदर्भ आयडी',
    selectRelation: 'नाते निवडा',
    chooseFile: 'फाइल निवडा',
    joinAsFamilyMember: 'कुटुंब सदस्य म्हणून सामील व्हा',
    spouse: 'जोडीदार',
    parent: 'पालक',
    child: 'मूल',
    sibling: 'भावंड',
    chats: 'चॅट्स',
    communities: 'समुदाय',
    broadcasts: 'प्रसारण',
    calls: 'कॉल्स',
    settings: 'सेटिंग्ज',
    profile: 'प्रोफाइल',
    searchChats: 'चॅट्स शोधा...',
    typeMessage: 'संदेश टाइप करा...',
    selectChatToStart: 'संदेश सुरू करण्यासाठी चॅट निवडा',
    selectCommunity: 'पाहण्यासाठी समुदाय निवडा',
    selectBroadcast: 'पाहण्यासाठी प्रसारण निवडा',
    members: 'सदस्य',
    recipients: 'प्राप्तकर्ते',
    editProfile: 'प्रोफाइल संपादित करा',
    logout: 'लॉगआउट',
    verifiedAccount: 'सत्यापित खाते',
    account: 'खाते',
    privacy: 'गोपनीयता',
    security: 'सुरक्षा',
    preferences: 'प्राधान्ये',
    darkMode: 'डार्क मोड',
    notifications: 'सूचना',
    about: 'बद्दल',
    aboutSuchak: 'SUCHAK बद्दल',
    e2eInfo: 'E2E एन्क्रिप्शन माहिती',
    calling: 'कॉल करत आहे...',
    missed: 'सुटलेले',
    endCall: 'कॉल समाप्त करा',
    online: 'ऑनलाइन',
    offline: 'ऑफलाइन',
    yesterday: 'काल',
    submit: 'सबमिट करा',
    cancel: 'रद्द करा',
  }},
  gujarati: { ...englishTranslations, ...{
    welcome: 'SUCHAK માં આપનું સ્વાગત છે',
    selectLanguage: 'ચાલુ રાખવા માટે ભાષા પસંદ કરો',
    getStarted: 'શરૂ કરો',
    defencePlatform: 'સંરક્ષણ સંચાર પ્લેટફોર્મ',
    enterPhone: 'તમારો ફોન નંબર દાખલ કરો',
    phoneNumber: 'ફોન નંબર',
    sendOTP: 'OTP મોકલો',
    newUser: 'નવા સરકારી વપરાશકર્તા? અહીં નોંધણી કરો',
    familyJoin: 'પરિવારના સભ્ય તરીકે જોડાઓ',
    encrypted: 'એન્ડ-ટુ-એન્ડ એન્ક્રિપ્ટેડ',
    register: 'નોંધણી કરો',
    createAccount: 'તમારું સુરક્ષિત ખાતું બનાવો',
    fullName: 'પૂરું નામ',
    serviceId: 'સેવા ID / વેટરન ID',
    aadhaarNumber: 'આધાર નંબર',
    alreadyHaveAccount: 'પહેલેથી ખાતું છે?',
    loginHere: 'લોગિન',
    familyMemberRegistration: 'પરિવાર સભ્ય નોંધણી',
    joinViaReference: 'સંદર્ભ ID અને ચકાસણી દ્વારા જોડાઓ',
    referenceId: 'સંદર્ભ ID',
    selectRelation: 'સંબંધ પસંદ કરો',
    chooseFile: 'ફાઇલ પસંદ કરો',
    joinAsFamilyMember: 'પરિવાર સભ્ય તરીકે જોડાઓ',
    spouse: 'જીવનસાથી',
    parent: 'માતાપિતા',
    child: 'બાળક',
    sibling: 'ભાઈબહેન',
    chats: 'ચેટ્સ',
    communities: 'સમુદાયો',
    broadcasts: 'પ્રસારણ',
    calls: 'કૉલ્સ',
    settings: 'સેટિંગ્સ',
    profile: 'પ્રોફાઇલ',
    searchChats: 'ચેટ્સ શોધો...',
    typeMessage: 'સંદેશ ટાઇપ કરો...',
    selectChatToStart: 'સંદેશ શરૂ કરવા માટે ચેટ પસંદ કરો',
    selectCommunity: 'જોવા માટે સમુદાય પસંદ કરો',
    selectBroadcast: 'જોવા માટે પ્રસારણ પસંદ કરો',
    members: 'સભ્યો',
    recipients: 'પ્રાપ્તકર્તાઓ',
    editProfile: 'પ્રોફાઇલ સંપાદિત કરો',
    logout: 'લોગઆઉટ',
    verifiedAccount: 'ચકાસાયેલ ખાતું',
    account: 'ખાતું',
    privacy: 'ગોપનીયતા',
    security: 'સુરક્ષા',
    preferences: 'પસંદગીઓ',
    darkMode: 'ડાર્ક મોડ',
    notifications: 'સૂચનાઓ',
    about: 'વિશે',
    aboutSuchak: 'SUCHAK વિશે',
    e2eInfo: 'E2E એન્ક્રિપ્શન માહિતી',
    calling: 'કૉલ કરી રહ્યાં છે...',
    missed: 'ચૂકી ગયેલ',
    endCall: 'કૉલ સમાપ્ત કરો',
    online: 'ઓનલાઇન',
    offline: 'ઓફલાઇન',
    yesterday: 'ગઈકાલે',
    submit: 'સબમિટ કરો',
    cancel: 'રદ કરો',
  }},
  punjabi: { ...englishTranslations, ...{
    welcome: 'SUCHAK ਵਿੱਚ ਤੁਹਾਡਾ ਸੁਆਗਤ ਹੈ',
    selectLanguage: 'ਜਾਰੀ ਰੱਖਣ ਲਈ ਭਾਸ਼ਾ ਚੁਣੋ',
    getStarted: 'ਸ਼ੁਰੂ ਕਰੋ',
    defencePlatform: 'ਰੱਖਿਆ ਸੰਚਾਰ ਪਲੇਟਫਾਰਮ',
    enterPhone: 'ਆਪਣਾ ਫ਼ੋਨ ਨੰਬਰ ਦਰਜ ਕਰੋ',
    phoneNumber: 'ਫ਼ੋਨ ਨੰਬਰ',
    sendOTP: 'OTP ਭੇਜੋ',
    newUser: 'ਨਵੇਂ ਸਰਕਾਰੀ ਉਪਭੋਗਤਾ? ਇੱਥੇ ਰਜਿਸਟਰ ਕਰੋ',
    familyJoin: 'ਪਰਿਵਾਰਕ ਮੈਂਬਰ ਵਜੋਂ ਸ਼ਾਮਲ ਹੋਵੋ',
    encrypted: 'ਐਂਡ-ਟੂ-ਐਂਡ ਐਨਕ੍ਰਿਪਟਡ',
    register: 'ਰਜਿਸਟਰ ਕਰੋ',
    createAccount: 'ਆਪਣਾ ਸੁਰੱਖਿਅਤ ਖਾਤਾ ਬਣਾਓ',
    fullName: 'ਪੂਰਾ ਨਾਮ',
    serviceId: 'ਸੇਵਾ ID / ਵੈਟਰਨ ID',
    aadhaarNumber: 'ਆਧਾਰ ਨੰਬਰ',
    alreadyHaveAccount: 'ਪਹਿਲਾਂ ਤੋਂ ਖਾਤਾ ਹੈ?',
    loginHere: 'ਲੌਗਇਨ',
    familyMemberRegistration: 'ਪਰਿਵਾਰਕ ਮੈਂਬਰ ਰਜਿਸਟ੍ਰੇਸ਼ਨ',
    joinViaReference: 'ਰੈਫਰੈਂਸ ID ਅਤੇ ਤਸਦੀਕ ਰਾਹੀਂ ਸ਼ਾਮਲ ਹੋਵੋ',
    referenceId: 'ਰੈਫਰੈਂਸ ID',
    selectRelation: 'ਰਿਸ਼ਤਾ ਚੁਣੋ',
    chooseFile: 'ਫਾਇਲ ਚੁਣੋ',
    joinAsFamilyMember: 'ਪਰਿਵਾਰਕ ਮੈਂਬਰ ਵਜੋਂ ਸ਼ਾਮਲ ਹੋਵੋ',
    spouse: 'ਜੀਵਨ ਸਾਥੀ',
    parent: 'ਮਾਤਾ-ਪਿਤਾ',
    child: 'ਬੱਚਾ',
    sibling: 'ਭੈਣ-ਭਰਾ',
    chats: 'ਚੈਟਸ',
    communities: 'ਕਮਿਊਨਿਟੀਜ਼',
    broadcasts: 'ਬ੍ਰੌਡਕਾਸਟਸ',
    calls: 'ਕਾਲਾਂ',
    settings: 'ਸੈਟਿੰਗਾਂ',
    profile: 'ਪ੍ਰੋਫਾਈਲ',
    searchChats: 'ਚੈਟਸ ਖੋਜੋ...',
    typeMessage: 'ਸੁਨੇਹਾ ਟਾਈਪ ਕਰੋ...',
    selectChatToStart: 'ਮੈਸੇਜਿੰਗ ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਚੈਟ ਚੁਣੋ',
    selectCommunity: 'ਦੇਖਣ ਲਈ ਕਮਿਊਨਿਟੀ ਚੁਣੋ',
    selectBroadcast: 'ਦੇਖਣ ਲਈ ਬ੍ਰੌਡਕਾਸਟ ਚੁਣੋ',
    members: 'ਮੈਂਬਰ',
    recipients: 'ਪ੍ਰਾਪਤਕਰਤਾ',
    editProfile: 'ਪ੍ਰੋਫਾਈਲ ਸੰਪਾਦਿਤ ਕਰੋ',
    logout: 'ਲੌਗਆਉਟ',
    verifiedAccount: 'ਤਸਦੀਕਸ਼ੁਦਾ ਖਾਤਾ',
    account: 'ਖਾਤਾ',
    privacy: 'ਗੋਪਨੀਯਤਾ',
    security: 'ਸੁਰੱਖਿਆ',
    preferences: 'ਤਰਜੀਹਾਂ',
    darkMode: 'ਡਾਰਕ ਮੋਡ',
    notifications: 'ਸੂਚਨਾਵਾਂ',
    about: 'ਬਾਰੇ',
    aboutSuchak: 'SUCHAK ਬਾਰੇ',
    e2eInfo: 'E2E ਐਨਕ੍ਰਿਪਸ਼ਨ ਜਾਣਕਾਰੀ',
    calling: 'ਕਾਲ ਕਰ ਰਿਹਾ ਹੈ...',
    missed: 'ਖੁੰਝੀ ਹੋਈ',
    endCall: 'ਕਾਲ ਖਤਮ ਕਰੋ',
    online: 'ਔਨਲਾਈਨ',
    offline: 'ਔਫਲਾਈਨ',
    yesterday: 'ਕੱਲ੍ਹ',
    submit: 'ਜਮ੍ਹਾਂ ਕਰੋ',
    cancel: 'ਰੱਦ ਕਰੋ',
  }},
  tamil: { ...englishTranslations, ...{
    welcome: 'SUCHAK இல் உங்களை வரவேற்கிறோம்',
    selectLanguage: 'தொடர ஒரு மொழியைத் தேர்ந்தெடுக்கவும்',
    getStarted: 'தொடங்கு',
    defencePlatform: 'பாதுகாப்பு தொடர்பு தளம்',
    enterPhone: 'உங்கள் தொலைபேசி எண்ணை உள்ளிடவும்',
    phoneNumber: 'தொலைபேசி எண்',
    sendOTP: 'OTP அனுப்பவும்',
    newUser: 'புதிய அரசு பயனர்? இங்கே பதிவு செய்யுங்கள்',
    familyJoin: 'குடும்ப உறுப்பினராக சேரவும்',
    encrypted: 'எண்ட்-டு-எண்ட் என்க்ரிப்ட்டட்',
    register: 'பதிவு செய்யுங்கள்',
    createAccount: 'உங்கள் பாதுகாப்பான கணக்கை உருவாக்கவும்',
    fullName: 'முழு பெயர்',
    serviceId: 'சேவை ID / மூத்தவர் ID',
    aadhaarNumber: 'ஆதார் எண்',
    alreadyHaveAccount: 'ஏற்கனவே கணக்கு உள்ளதா?',
    loginHere: 'உள்நுழைக',
    familyMemberRegistration: 'குடும்ப உறுப்பினர் பதிவு',
    joinViaReference: 'குறிப்பு ID மற்றும் சரிபார்ப்பு மூலம் சேரவும்',
    referenceId: 'குறிப்பு ID',
    selectRelation: 'உறவை தேர்ந்தெடுக்கவும்',
    chooseFile: 'கோப்பை தேர்ந்தெடுக்கவும்',
    joinAsFamilyMember: 'குடும்ப உறுப்பினராக சேரவும்',
    spouse: 'வாழ்க்கைத் துணை',
    parent: 'பெற்றோர்',
    child: 'குழந்தை',
    sibling: 'உடன்பிறந்தவர்',
    chats: 'அரட்டைகள்',
    communities: 'சமூகங்கள்',
    broadcasts: 'ஒளிபரப்புகள்',
    calls: 'அழைப்புகள்',
    settings: 'அமைப்புகள்',
    profile: 'சுயவிவரம்',
    searchChats: 'அரட்டைகளைத் தேடு...',
    typeMessage: 'செய்தியை தட்டச்சு செய்க...',
    selectChatToStart: 'செய்தியிடலைத் தொடங்க அரட்டையைத் தேர்ந்தெடுக்கவும்',
    selectCommunity: 'காண சமூகத்தைத் தேர்ந்தெடுக்கவும்',
    selectBroadcast: 'காண ஒளிபரப்பைத் தேர்ந்தெடுக்கவும்',
    members: 'உறுப்பினர்கள்',
    recipients: 'பெறுநர்கள்',
    editProfile: 'சுயவிவரத்தைத் திருத்து',
    logout: 'வெளியேறு',
    verifiedAccount: 'சரிபார்க்கப்பட்ட கணக்கு',
    account: 'கணக்கு',
    privacy: 'தனியுரிமை',
    security: 'பாதுகாப்பு',
    preferences: 'விருப்பத்தேர்வுகள்',
    darkMode: 'இருண்ட பயன்முறை',
    notifications: 'அறிவிப்புகள்',
    about: 'பற்றி',
    aboutSuchak: 'SUCHAK பற்றி',
    e2eInfo: 'E2E என்க்ரிப்ஷன் தகவல்',
    calling: 'அழைக்கிறது...',
    missed: 'தவறவிட்டது',
    endCall: 'அழைப்பை முடிக்கவும்',
    online: 'ஆன்லைன்',
    offline: 'ஆஃப்லைன்',
    yesterday: 'நேற்று',
    submit: 'சமர்ப்பிக்கவும்',
    cancel: 'ரத்துசெய்',
  }},
  bengali: { ...englishTranslations, ...{
    welcome: 'SUCHAK-এ আপনাকে স্বাগতম',
    selectLanguage: 'চালিয়ে যেতে একটি ভাষা নির্বাচন করুন',
    getStarted: 'শুরু করুন',
    defencePlatform: 'প্রতিরক্ষা যোগাযোগ প্ল্যাটফর্ম',
    enterPhone: 'আপনার ফোন নম্বর লিখুন',
    phoneNumber: 'ফোন নম্বর',
    sendOTP: 'OTP পাঠান',
    newUser: 'নতুন সরকারি ব্যবহারকারী? এখানে নিবন্ধন করুন',
    familyJoin: 'পরিবারের সদস্য হিসেবে যোগ দিন',
    encrypted: 'এন্ড-টু-এন্ড এনক্রিপ্টেড',
    register: 'নিবন্ধন করুন',
    createAccount: 'আপনার সুরক্ষিত অ্যাকাউন্ট তৈরি করুন',
    fullName: 'পুরো নাম',
    serviceId: 'সেবা ID / প্রবীণ ID',
    aadhaarNumber: 'আধার নম্বর',
    alreadyHaveAccount: 'ইতিমধ্যে অ্যাকাউন্ট আছে?',
    loginHere: 'লগইন',
    familyMemberRegistration: 'পরিবারের সদস্য নিবন্ধন',
    joinViaReference: 'রেফারেন্স ID এবং যাচাইকরণের মাধ্যমে যোগ দিন',
    referenceId: 'রেফারেন্স ID',
    selectRelation: 'সম্পর্ক নির্বাচন করুন',
    chooseFile: 'ফাইল নির্বাচন করুন',
    joinAsFamilyMember: 'পরিবারের সদস্য হিসেবে যোগ দিন',
    spouse: 'স্বামী/স্ত্রী',
    parent: 'পিতামাতা',
    child: 'সন্তান',
    sibling: 'ভাইবোন',
    chats: 'চ্যাট',
    communities: 'সম্প্রদায়',
    broadcasts: 'সম্প্রচার',
    calls: 'কল',
    settings: 'সেটিংস',
    profile: 'প্রোফাইল',
    searchChats: 'চ্যাট খুঁজুন...',
    typeMessage: 'বার্তা টাইপ করুন...',
    selectChatToStart: 'বার্তা শুরু করতে একটি চ্যাট নির্বাচন করুন',
    selectCommunity: 'দেখার জন্য একটি সম্প্রদায় নির্বাচন করুন',
    selectBroadcast: 'দেখার জন্য একটি সম্প্রচার নির্বাচন করুন',
    members: 'সদস্য',
    recipients: 'প্রাপক',
    editProfile: 'প্রোফাইল সম্পাদনা করুন',
    logout: 'লগআউট',
    verifiedAccount: 'যাচাইকৃত অ্যাকাউন্ট',
    account: 'অ্যাকাউন্ট',
    privacy: 'গোপনীয়তা',
    security: 'নিরাপত্তা',
    preferences: 'পছন্দসমূহ',
    darkMode: 'ডার্ক মোড',
    notifications: 'বিজ্ঞপ্তি',
    about: 'সম্পর্কে',
    aboutSuchak: 'SUCHAK সম্পর্কে',
    e2eInfo: 'E2E এনক্রিপশন তথ্য',
    calling: 'কল করছে...',
    missed: 'মিস',
    endCall: 'কল শেষ করুন',
    online: 'অনলাইন',
    offline: 'অফলাইন',
    yesterday: 'গতকাল',
    submit: 'জমা দিন',
    cancel: 'বাতিল',
  }},
  telugu: { ...englishTranslations, ...{
    welcome: 'SUCHAK కి స్వాగతం',
    selectLanguage: 'కొనసాగించడానికి భాషను ఎంచుకోండి',
    getStarted: 'ప్రారంభించండి',
    defencePlatform: 'రక్షణ కమ్యూనికేషన్ ప్లాట్‌ఫారమ్',
    enterPhone: 'మీ ఫోన్ నంబర్‌ను నమోదు చేయండి',
    phoneNumber: 'ఫోన్ నంబర్',
    sendOTP: 'OTP పంపండి',
    newUser: 'కొత్త ప్రభుత్వ వినియోగదారు? ఇక్కడ నమోదు చేయండి',
    familyJoin: 'కుటుంబ సభ్యునిగా చేరండి',
    encrypted: 'ఎండ్-టు-ఎండ్ ఎన్‌క్రిప్ట్ చేయబడింది',
    register: 'నమోదు చేయండి',
    createAccount: 'మీ సురక్షిత ఖాతాను సృష్టించండి',
    fullName: 'పూర్తి పేరు',
    serviceId: 'సేవా ID / అనుభవజ్ఞుడు ID',
    aadhaarNumber: 'ఆధార్ నంబర్',
    alreadyHaveAccount: 'ఇప్పటికే ఖాతా ఉందా?',
    loginHere: 'లాగిన్',
    familyMemberRegistration: 'కుటుంబ సభ్యుల నమోదు',
    joinViaReference: 'రిఫరెన్స్ ID మరియు ధృవీకరణ ద్వారా చేరండి',
    referenceId: 'రిఫరెన్స్ ID',
    selectRelation: 'సంబంధాన్ని ఎంచుకోండి',
    chooseFile: 'ఫైల్‌ను ఎంచుకోండి',
    joinAsFamilyMember: 'కుటుంబ సభ్యునిగా చేరండి',
    spouse: 'జీవిత భాగస్వామి',
    parent: 'తల్లిదండ్రులు',
    child: 'పిల్లవాడు',
    sibling: 'తోబుట్టువు',
    chats: 'చాట్‌లు',
    communities: 'కమ్యూనిటీలు',
    broadcasts: 'ప్రసారాలు',
    calls: 'కాల్స్',
    settings: 'సెట్టింగులు',
    profile: 'ప్రొఫైల్',
    searchChats: 'చాట్‌లను శోధించండి...',
    typeMessage: 'సందేశాన్ని టైప్ చేయండి...',
    selectChatToStart: 'సందేశ పంపడం ప్రారంభించడానికి చాట్‌ను ఎంచుకోండి',
    selectCommunity: 'వీక్షించడానికి కమ్యూనిటీని ఎంచుకోండి',
    selectBroadcast: 'వీక్షించడానికి ప్రసారాన్ని ఎంచుకోండి',
    members: 'సభ్యులు',
    recipients: 'గ్రహీతలు',
    editProfile: 'ప్రొఫైల్ సవరించండి',
    logout: 'లాగౌట్',
    verifiedAccount: 'ధృవీకరించబడిన ఖాతా',
    account: 'ఖాతా',
    privacy: 'గోప్యత',
    security: 'భద్రత',
    preferences: 'ప్రాధాన్యతలు',
    darkMode: 'డార్క్ మోడ్',
    notifications: 'నోటిఫికేషన్‌లు',
    about: 'గురించి',
    aboutSuchak: 'SUCHAK గురించి',
    e2eInfo: 'E2E ఎన్‌క్రిప్షన్ సమాచారం',
    calling: 'కాల్ చేస్తోంది...',
    missed: 'మిస్ అయ్యారు',
    endCall: 'కాల్ ముగించండి',
    online: 'ఆన్‌లైన్',
    offline: 'ఆఫ్‌లైన్',
    yesterday: 'నిన్న',
    submit: 'సమర్పించండి',
    cancel: 'రద్దు చేయండి',
  }},
  kannada: { ...englishTranslations, ...{
    welcome: 'SUCHAK ಗೆ ಸುಸ್ವಾಗತ',
    selectLanguage: 'ಮುಂದುವರಿಸಲು ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    getStarted: 'ಪ್ರಾರಂಭಿಸಿ',
    defencePlatform: 'ರಕ್ಷಣಾ ಸಂವಹನ ವೇದಿಕೆ',
    enterPhone: 'ನಿಮ್ಮ ಫೋನ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ',
    phoneNumber: 'ಫೋನ್ ಸಂಖ್ಯೆ',
    sendOTP: 'OTP ಕಳುಹಿಸಿ',
    newUser: 'ಹೊಸ ಸರ್ಕಾರಿ ಬಳಕೆದಾರ? ಇಲ್ಲಿ ನೋಂದಾಯಿಸಿ',
    familyJoin: 'ಕುಟುಂಬ ಸದಸ್ಯರಾಗಿ ಸೇರಿ',
    encrypted: 'ಎಂಡ್-ಟು-ಎಂಡ್ ಎನ್‌ಕ್ರಿಪ್ಟ್ ಮಾಡಲಾಗಿದೆ',
    register: 'ನೋಂದಾಯಿಸಿ',
    createAccount: 'ನಿಮ್ಮ ಸುರಕ್ಷಿತ ಖಾತೆಯನ್ನು ರಚಿಸಿ',
    fullName: 'ಪೂರ್ಣ ಹೆಸರು',
    serviceId: 'ಸೇವಾ ID / ಪರಿಣತರ ID',
    aadhaarNumber: 'ಆಧಾರ್ ಸಂಖ್ಯೆ',
    alreadyHaveAccount: 'ಈಗಾಗಲೇ ಖಾತೆ ಹೊಂದಿದ್ದೀರಾ?',
    loginHere: 'ಲಾಗಿನ್',
    familyMemberRegistration: 'ಕುಟುಂಬ ಸದಸ್ಯರ ನೋಂದಣಿ',
    joinViaReference: 'ಉಲ್ಲೇಖ ID ಮತ್ತು ಪರಿಶೀಲನೆ ಮೂಲಕ ಸೇರಿ',
    referenceId: 'ಉಲ್ಲೇಖ ID',
    selectRelation: 'ಸಂಬಂಧವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    chooseFile: 'ಫೈಲ್ ಆಯ್ಕೆಮಾಡಿ',
    joinAsFamilyMember: 'ಕುಟುಂಬ ಸದಸ್ಯರಾಗಿ ಸೇರಿ',
    spouse: 'ಜೀವನ ಸಂಗಾತಿ',
    parent: 'ಪೋಷಕರು',
    child: 'ಮಗು',
    sibling: 'ಒಡಹುಟ್ಟಿದವರು',
    chats: 'ಚಾಟ್‌ಗಳು',
    communities: 'ಸಮುದಾಯಗಳು',
    broadcasts: 'ಪ್ರಸಾರಗಳು',
    calls: 'ಕರೆಗಳು',
    settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    profile: 'ಪ್ರೊಫೈಲ್',
    searchChats: 'ಚಾಟ್‌ಗಳನ್ನು ಹುಡುಕಿ...',
    typeMessage: 'ಸಂದೇಶವನ್ನು ಟೈಪ್ ಮಾಡಿ...',
    selectChatToStart: 'ಸಂದೇಶ ಕಳುಹಿಸುವುದನ್ನು ಪ್ರಾರಂಭಿಸಲು ಚಾಟ್ ಆಯ್ಕೆಮಾಡಿ',
    selectCommunity: 'ವೀಕ್ಷಿಸಲು ಸಮುದಾಯವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    selectBroadcast: 'ವೀಕ್ಷಿಸಲು ಪ್ರಸಾರವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    members: 'ಸದಸ್ಯರು',
    recipients: 'ಸ್ವೀಕರಿಸುವವರು',
    editProfile: 'ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ',
    logout: 'ಲಾಗೌಟ್',
    verifiedAccount: 'ಪರಿಶೀಲಿಸಿದ ಖಾತೆ',
    account: 'ಖಾತೆ',
    privacy: 'ಗೌಪ್ಯತೆ',
    security: 'ಭದ್ರತೆ',
    preferences: 'ಆದ್ಯತೆಗಳು',
    darkMode: 'ಡಾರ್ಕ್ ಮೋಡ್',
    notifications: 'ಅಧಿಸೂಚನೆಗಳು',
    about: 'ಕುರಿತು',
    aboutSuchak: 'SUCHAK ಕುರಿತು',
    e2eInfo: 'E2E ಎನ್‌ಕ್ರಿಪ್ಶನ್ ಮಾಹಿತಿ',
    calling: 'ಕರೆ ಮಾಡುತ್ತಿದೆ...',
    missed: 'ತಪ್ಪಿದ',
    endCall: 'ಕರೆ ಕೊನೆಗೊಳಿಸಿ',
    online: 'ಆನ್‌ಲೈನ್',
    offline: 'ಆಫ್‌ಲೈನ್',
    yesterday: 'ನಿನ್ನೆ',
    submit: 'ಸಲ್ಲಿಸಿ',
    cancel: 'ರದ್ದುಮಾಡಿ',
  }},
  malayalam: { ...englishTranslations, ...{
    welcome: 'SUCHAK-ലേക്ക് സ്വാഗതം',
    selectLanguage: 'തുടരാൻ ഒരു ഭാഷ തിരഞ്ഞെടുക്കുക',
    getStarted: 'ആരംഭിക്കുക',
    defencePlatform: 'പ്രതിരോധ ആശയവിനിമയ പ്ലാറ്റ്‌ഫോം',
    enterPhone: 'നിങ്ങളുടെ ഫോൺ നമ്പർ നൽകുക',
    phoneNumber: 'ഫോൺ നമ്പർ',
    sendOTP: 'OTP അയയ്ക്കുക',
    newUser: 'പുതിയ സർക്കാർ ഉപയോക്താവ്? ഇവിടെ രജിസ്റ്റർ ചെയ്യുക',
    familyJoin: 'കുടുംബാംഗമായി ചേരുക',
    encrypted: 'എൻഡ്-ടു-എൻഡ് എൻക്രിപ്റ്റ് ചെയ്തത്',
    register: 'രജിസ്റ്റർ ചെയ്യുക',
    createAccount: 'നിങ്ങളുടെ സുരക്ഷിത അക്കൗണ്ട് സൃഷ്ടിക്കുക',
    fullName: 'പൂർണ്ണ പേര്',
    serviceId: 'സേവന ID / വെറ്ററൻ ID',
    aadhaarNumber: 'ആധാർ നമ്പർ',
    alreadyHaveAccount: 'ഇതിനകം അക്കൗണ്ട് ഉണ്ടോ?',
    loginHere: 'ലോഗിൻ',
    familyMemberRegistration: 'കുടുംബാംഗ രജിസ്ട്രേഷൻ',
    joinViaReference: 'റഫറൻസ് ID, പരിശോധനയിലൂടെ ചേരുക',
    referenceId: 'റഫറൻസ് ID',
    selectRelation: 'ബന്ധം തിരഞ്ഞെടുക്കുക',
    chooseFile: 'ഫയൽ തിരഞ്ഞെടുക്കുക',
    joinAsFamilyMember: 'കുടുംബാംഗമായി ചേരുക',
    spouse: 'ഇണ',
    parent: 'മാതാപിതാക്കൾ',
    child: 'കുട്ടി',
    sibling: 'സഹോദരൻ/സഹോദരി',
    chats: 'ചാറ്റുകൾ',
    communities: 'കമ്മ്യൂണിറ്റികൾ',
    broadcasts: 'പ്രക്ഷേപണങ്ങൾ',
    calls: 'കോളുകൾ',
    settings: 'ക്രമീകരണങ്ങൾ',
    profile: 'പ്രൊഫൈൽ',
    searchChats: 'ചാറ്റുകൾ തിരയുക...',
    typeMessage: 'സന്ദേശം ടൈപ്പ് ചെയ്യുക...',
    selectChatToStart: 'സന്ദേശമയയ്ക്കൽ ആരംഭിക്കാൻ ചാറ്റ് തിരഞ്ഞെടുക്കുക',
    selectCommunity: 'കാണാൻ കമ്മ്യൂണിറ്റി തിരഞ്ഞെടുക്കുക',
    selectBroadcast: 'കാണാൻ പ്രക്ഷേപണം തിരഞ്ഞെടുക്കുക',
    members: 'അംഗങ്ങൾ',
    recipients: 'സ്വീകർത്താക്കൾ',
    editProfile: 'പ്രൊഫൈൽ എഡിറ്റ് ചെയ്യുക',
    logout: 'ലോഗൗട്ട്',
    verifiedAccount: 'പരിശോധിച്ച അക്കൗണ്ട്',
    account: 'അക്കൗണ്ട്',
    privacy: 'സ്വകാര്യത',
    security: 'സുരക്ഷ',
    preferences: 'മുൻഗണനകൾ',
    darkMode: 'ഡാർക്ക് മോഡ്',
    notifications: 'അറിയിപ്പുകൾ',
    about: 'കുറിച്ച്',
    aboutSuchak: 'SUCHAK കുറിച്ച്',
    e2eInfo: 'E2E എൻക്രിപ്ഷൻ വിവരങ്ങൾ',
    calling: 'വിളിക്കുന്നു...',
    missed: 'മിസ്സ് ചെയ്തത്',
    endCall: 'കോൾ അവസാനിപ്പിക്കുക',
    online: 'ഓൺലൈൻ',
    offline: 'ഓഫ്‌ലൈൻ',
    yesterday: 'ഇന്നലെ',
    submit: 'സമർപ്പിക്കുക',
    cancel: 'റദ്ദാക്കുക',
  }},
  urdu: { ...englishTranslations, ...{
    welcome: 'SUCHAK میں خوش آمدید',
    selectLanguage: 'جاری رکھنے کے لیے زبان منتخب کریں',
    getStarted: 'شروع کریں',
    defencePlatform: 'دفاعی رابطہ پلیٹ فارم',
    enterPhone: 'اپنا فون نمبر درج کریں',
    phoneNumber: 'فون نمبر',
    sendOTP: 'OTP بھیجیں',
    newUser: 'نیا سرکاری صارف؟ یہاں رجسٹر کریں',
    familyJoin: 'خاندان کے رکن کے طور پر شامل ہوں',
    encrypted: 'اینڈ ٹو اینڈ خفیہ کاری',
    register: 'رجسٹر کریں',
    createAccount: 'اپنا محفوظ اکاؤنٹ بنائیں',
    fullName: 'مکمل نام',
    serviceId: 'سروس ID / ویٹرن ID',
    aadhaarNumber: 'آدھار نمبر',
    alreadyHaveAccount: 'پہلے سے اکاؤنٹ ہے؟',
    loginHere: 'لاگ ان',
    familyMemberRegistration: 'خاندان کے رکن کی رجسٹریشن',
    joinViaReference: 'حوالہ ID اور تصدیق کے ذریعے شامل ہوں',
    referenceId: 'حوالہ ID',
    selectRelation: 'رشتہ منتخب کریں',
    chooseFile: 'فائل منتخب کریں',
    joinAsFamilyMember: 'خاندان کے رکن کے طور پر شامل ہوں',
    spouse: 'شریک حیات',
    parent: 'والدین',
    child: 'بچہ',
    sibling: 'بہن/بھائی',
    chats: 'چیٹس',
    communities: 'کمیونٹیز',
    broadcasts: 'براڈکاسٹس',
    calls: 'کالز',
    settings: 'ترتیبات',
    profile: 'پروفائل',
    searchChats: 'چیٹس تلاش کریں...',
    typeMessage: 'پیغام ٹائپ کریں...',
    selectChatToStart: 'پیغام رسانی شروع کرنے کے لیے چیٹ منتخب کریں',
    selectCommunity: 'دیکھنے کے لیے کمیونٹی منتخب کریں',
    selectBroadcast: 'دیکھنے کے لیے براڈکاسٹ منتخب کریں',
    members: 'اراکین',
    recipients: 'وصول کنندگان',
    editProfile: 'پروفائل میں ترمیم کریں',
    logout: 'لاگ آؤٹ',
    verifiedAccount: 'تصدیق شدہ اکاؤنٹ',
    account: 'اکاؤنٹ',
    privacy: 'رازداری',
    security: 'سیکیورٹی',
    preferences: 'ترجیحات',
    darkMode: 'ڈارک موڈ',
    notifications: 'اطلاعات',
    about: 'کے بارے میں',
    aboutSuchak: 'SUCHAK کے بارے میں',
    e2eInfo: 'E2E انکرپشن معلومات',
    calling: 'کال کر رہا ہے...',
    missed: 'چھوٹ گئی',
    endCall: 'کال ختم کریں',
    online: 'آن لائن',
    offline: 'آف لائن',
    yesterday: 'کل',
    submit: 'جمع کریں',
    cancel: 'منسوخ کریں',
  }},
};

interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  t: Translations;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState('english');

  const t = translations[language] || translations.english;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
